language: java
dist: trusty
sudo: required
jdk:
  - openjdk7
  - oraclejdk8
before_script: openssl s_client -CApath /etc/ssl/certs/ -connect plugins.gradle.org:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt; sudo keytool -importcert -noprompt -file /tmp/gradle.crt -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -alias root -storepass changeit;
script: for mod in cadc-vos cadc-vos-server cadc-test-vos cavern; do cd $mod; gradle --full-stacktrace --info -Djava.io.tmpdir=/tmp -Duser.name=fred build javadoc install || break -1; cd ..; done
